spring.application.name=shipment-service

# Perfil activo
spring.profiles.active=dev

# Puerto dinámico (Render)
server.port=${PORT:8080}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# Login
login.max-attempts=5
login.lock-time-ms=600000

# SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true