spring.application.name=shipment-service
# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_shipment
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true                  
spring.jpa.hibernate.ddl-auto=update

# ===============================
# Configuración general
# ===============================
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Puerto del servidor
# ===============================
server.port=8080

#jwt
#================================
spring.security.jwt.secret=A72hJZtkTfYoiasCoFhAtC2Ea89blc7BrjnhSdcnNvo=
spring.security.jwt.expiration=3600000

#attempt
#================================
login.max-attempts=5
login.lock-time-ms=600000

