spring.application.name=shipment-service

# Puerto dinámico (Render)
server.port=${PORT:8080}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# JWT
spring.security.jwt.secret=${JWT_SECRET}
spring.security.jwt.expiration=${JWT_EXPIRATION}

# Login
login.max-attempts=5
login.lock-time-ms=600000